:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - low
:schedule:
  sync_talent_with_notion:
    cron: '0 20 * * *' # Runs once every wednesday at 5pm
    class: SyncTalentWithNotionJob
