:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - low
:schedule:
  send_notification_digests:
    cron: '0 1 * * *'
    class: SendNotificationDigestsJob
  sync_talent_with_notion:
    cron: '0 20 * * *' # Runs once every wednesday at 5pm
    class: SyncTalentWithNotionJob
